version: "3.8"
services:
  db:
    image: mysql
    ports:
      - 3308:3306
    environment:
      MYSQL_USER: raj
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: main
  redis:
    image: redis
    command: "redis-server --requirepass secret"
  server:
   build: ./server
   ports: 
    - "4000:80"
   volumes:
     - ./server:/app
     - /app/node_modules
     - /app/dist
   environment:
    PORT: 80
    DB_USERNAME: root
    DB_PASSWORD: secret
    DB_HOST: db
    DB_PORT: 3306
    DB_DATABASE: main
  